### PR TITLE
Add package.json file for easy installing via npm

### LINKED ISSUE #9: Add package.json?
Would it be possible to add a package.json file (and possibly even publish to npm).
It'd make it slightly easier to install via npm. 

```sh
$ npm i Noitidart/ostypes -D

npm ERR! addLocal Could not install /var/folders/qc/g_f0szh95k1fzph34rhmf5jw0000gp/T/npm-37620-cbda1b4d/git-cache-ad8eb847/cba5d9fd34cea3dd89da31aa2e2ccbdf89a066bf
npm ERR! addLocal Could not install /var/folders/qc/g_f0szh95k1fzph34rhmf5jw0000gp/T/npm-37620-cbda1b4d/git-cache-674f1560/cba5d9fd34cea3dd89da31aa2e2ccbdf89a066bf
npm ERR! addLocal Could not install /var/folders/qc/g_f0szh95k1fzph34rhmf5jw0000gp/T/npm-37620-cbda1b4d/git-cache-e7b38fa8/cba5d9fd34cea3dd89da31aa2e2ccbdf89a066bf
npm ERR! Darwin 16.1.0
npm ERR! argv "/Users/pdehaan/.nvm/versions/node/v6.9.0/bin/node" "/Users/pdehaan/.nvm/versions/node/v6.9.0/bin/npm" "i" "Noitidart/ostypes" "-D"
npm ERR! node v6.9.0
npm ERR! npm  v3.10.8
npm ERR! code EISDIR
npm ERR! errno -21
npm ERR! syscall read

npm ERR! eisdir EISDIR: illegal operation on a directory, read
npm ERR! eisdir This is most likely not a problem with npm itself
npm ERR! eisdir and is related to npm not being able to find a package.json in
npm ERR! eisdir a package you are trying to install.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/pdehaan/dev/github/mozilla/min-vid/npm-debug.log
```

### PR DESCRIPTION
**Pull request by pdehaan**
Fixes #9

### CODE REVIEW

**Comment by Noitidart** [comment]
Super cool thank you very much!

**Comment by Noitidart** [comment]
Do I have to npm publish now to get it onto npm?

Is it setup for use in an SDK addon though? (ostypes is not in CommonJS format)
I tried once to use npm with Addon SDK (jpm) but couldn't figure it out.

**Comment by pdehaan** [comment]
Currently (now that you've merged into **master**), you can install it using _npm_ or _yarn_ using one of the following commands:
- `npm i Noitidart/ostypes -D`
- `yarn add Noitidart/ostypes --dev`

Both of those should add it to the GitHub URL to your local package.json devDependencies:

``` js
"ostypes": "github:noitidart/ostypes",
```

After that, you're pretty much on your own. You'd need to do some package.json postinstall script (or whatever) to move the files into ./lib/vendor, etc.

If you want to add this to npm so you can "optimize" to `npm i ostypes -D` and do versioning and all that jazz, you'd just have to sign into npm via CLI and do `npm publish` -- https://www.npmjs.com/package/ostypes has some pretty solid instructions since the package name is still available.

**Comment by Noitidart** [comment]
Thanks @pdehaan! If anything else is needed to make it easier for your side let me know please.

I'll look into that npm stuff and see how I can maintain it as a git submodule, as its used in a few projects already as git submodule.

**Pull request merged**
