### PR TITLE
MessageBox + CreateTimerQueueTimer

### PR DESCRIPTION
**Pull request by tofutim**
The MessageBox works fine, however, I'm still having problems with CreateTimerQueueTimer. The timer runs and a signal is sent, but the moment it is, Firefox crashes. It is really quite dramatic. Currently I'm calling it with

```
function jsCallback(lpParameter, TimerOrWaitFired) {
  self.postMessage('lpParameter: ' + lpParameter);
  self.PostMessage('TimerOrWaitFired: ' + TimerOrWaitFired);
  return undefined;
}

var hNewTimer = ostypes.TYPE.HANDLE(0);
ret = ostypes.API('CreateTimerQueueTimer')(
  hNewTimer.address(),
  ostypes.TYPE.HANDLE(0),
  ostypes.TYPE.WAITORTIMERCALLBACK.ptr(jsCallback),
  ostypes.TYPE.PVOID(0),
  5000,
  0,
  0x00000000
);
```

It waits 5000 ms, then Firefox crashes. Any tips much appreciated.

### CODE REVIEW

**Comment by Noitidart** [comment]
Wow this is so fun working togather thanks!

I have to make some fixes on this. Can I do that before merging? Or do I have to merge first?

For instance `ifdef_UNICODE ? 'MessageBoxW' : 'MessageBox'` should be `ifdef_UNICODE ? 'MessageBoxW' : 'MessageBoxA'` (there is an A instead of W)

I'll test out creattimer in a playground

**Comment by tofutim** [comment]
Oops, sorry about that. I think you merge into another branch, make your fix and then merge into your main branch? At least that is what I would do. But I can also change it.

I think my code crashes because the callback goes out of scope.

**Comment by Noitidart** [comment]
Ah I'll try that make a branch thing I need to learn this collaborative stuff.

Ah yes you have to define it globally to keep it from getting GC'ed.

**Comment by tofutim** [comment]
just pushed the A. globally I'll have to see how to do that.

**Comment by tofutim** [comment]
https://github.com/tofutim/somnus - my test project

**Comment by tofutim** [comment]
i'm not sure how to make my callback global :(

**Comment by Noitidart** [comment]
I created a playground right here with ostypes imported to the mainthread - https://github.com/Noitidart/ostypes_playground

I'll test the callbck there

**Comment by Noitidart** [comment]
This was super cool thanks! Ill update my playground to this ostypes and test it out

**Pull request merged**
