### PR TITLE
ReadFileEx/WriteFileEx, overlapped

### PR DESCRIPTION
**Pull request by tofutim**
Noit, what are you using for an editor? I should just use what you use.

### CODE REVIEW

**Comment by Noitidart** [comment]
Thanks so much for this collaboration on this. It's a really a great collection we got going here. Anyone should be able plop it in and use it.

I actually use Notepad++ (and sublime for some snippets). I don't do anything special though. Just the spacing I set to tab but its no big deal. Any editor should work. Thanks so much for your effort to match my style.

Which editor do you use?

**Comment by tofutim** [comment]
Do you use tabs or spaces?

**Comment by Noitidart** [comment]
I use tabs :)

**Comment by tofutim** [comment]
I've been using Atom.io

**Comment by Noitidart** [comment]
Ah I've been meaning to check that out. I'll give that a look this weekend.
:)

**Pull request merged**
